"""empty message

Revision ID: 4deb9f6b5e74
Revises: 637f33b521b4
Create Date: 2020-04-22 07:14:04.564481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4deb9f6b5e74'
down_revision = '637f33b521b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('image_url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'image_url')
    # ### end Alembic commands ###
